version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sige-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sige
    ports:
      - "5432:5432"
    volumes:
      - sige_data:/var/lib/postgresql/data

volumes:
  sige_data: